version: '2.1'

services:
  duplicati:
    image: linuxserver/duplicati:latest
    container_name: duplicati
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
    volumes:
      - your-config-dir:/config
      - your-backups-dir:/backups
      - your-want-backup-dir:/some-dir
    ports:
      - 8200:8200
    restart: unless-stopped