version: '3.8'

services:
  redroid:
    image: redroid/redroid:13.0.0-latest
    container_name: redroid
    privileged: true
    restart: always
    ports:
      - 5555:5555
    volumes:
      - your-data-dir:/data
    command:
      - androidboot.redroid_gpu_mode=guest
      - redroid.width=1080
      - redroid.height=1920
      - androidboot.redroid_dpi=480
      - androidboot.hardware=mt6891
      - ro.secure=0
      - ro.boot.hwc=GLOBAL
      - ro.ril.oem.imei=861503068361145
      - ro.ril.oem.imei1=861503068361145
      - ro.ril.oem.imei2=861503068361148
      - ro.ril.miui.imei0=861503068361148
      - ro.product.manufacturer=Xiaomi
      - ro.build.product=chopin